# Generated by Django 2.2.17 on 2021-03-14 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.ImageField(blank=True, max_length=64, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 13, 13, 11, 40257, tzinfo=utc)),
        ),
    ]
